language: node_js

node_js:
  - "8"

install:
  - yarn

script:
  - yarn test:report

before_deploy:
  - npm i -g now

deploy:
  provider: script
  script: now -t $NOW_TOKEN -A now.demo.json -S datopian1 && now -t $NOW_TOKEN -A now.eds.json -S datopian1
  on:
    branch: master
