language: node_js

node_js:
  - "8"

install:
  - yarn

script:
  - yarn test:report

before_deploy:
  - npm i -g now

deploy:
  provider: script
  script: now alias frontend-v2-anuveyatsu.datopian1.now.sh frontend-v2-demo.now.sh -t $NOW_TOKEN -A now.demo.json -S datopian1 && now alias frontend-v2-anuveyatsu.datopian1.now.sh frontend-v2-eds.now.sh -t $NOW_TOKEN -A now.eds.json -S datopian1
  on:
    branch: master
