language: node_js

node_js:
  - "8"

install:
  - yarn

script:
  - yarn test:report

before_deploy:
  - npm i -g now

deploy:
  provider: script
  script: now switch datopian1 -t $NOW_TOKEN && now -t $NOW_TOKEN -A now.demo.json
  on:
    branch: master
